name: Docker Build and Push

on:
  push:
    branches:
      - main  # 或你希望触发工作的分支

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Docker registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}  # 使用 GitHub 的用户名
          password: ${{ secrets.YM_GITHUB_TOKEN }}  # 使用你添加到 Secrets 中的 token

      - name: Pull Docker image
        run: |
          docker pull ghcr.io/hjpwyb/docker/whyour/qinglong:latest  # 用你实际的镜像路径替换

      - name: Tag Docker image
        run: |
          docker tag ghcr.io/hjpwyb/docker/whyour/qinglong:latest ghcr.io/${{ github.repository_owner }}/whyour/qinglong:latest  # 替换为你的目标镜像路径

      - name: Push Docker image to GitHub Packages
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/whyour/qinglong:latest  # 推送镜像到 GitHub 容器注册表
